# Generated by Django 5.0.3 on 2024-03-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid',
            new_name='uid',
        ),
    ]
