# Generated by Django 5.0.3 on 2024-03-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='prdouctimage',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='uid',
        ),
    ]
