# Generated by Django 5.0.3 on 2024-03-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Coupon_code',
            new_name='coupon_code',
        ),
    ]
